import Link from "next/link";
import { db } from "@/db";
import { ticketEvents, workpapers } from "@/db/schema";
import { ensureSeeded } from "@/lib/persist";
import { desc } from "drizzle-orm";
import { runSimulation } from "@/lib/engine";

export const dynamic = "force-dynamic";

export default async function LedgerPage() {
  await ensureSeeded();
  const papers = await db.select().from(workpapers).orderBy(desc(workpapers.createdAt));
  const events = await db.select().from(ticketEvents).orderBy(desc(ticketEvents.createdAt)).limit(36);
  const on = runSimulation("watchdog_on");

  return (
    <main className="mx-auto max-w-[1440px] px-5 py-10">
      <p className="kicker">Signed state transitions</p>
      <h1 className="font-display mt-2 text-4xl font-extrabold tracking-tight">ISA 230 ledger</h1>
      <p className="mt-3 max-w-2xl text-[#c8c3b8]">
        Every tool call carries a parent hash, a working-prompt hash, and a step hash. The Merkle root is the
        audit seal. Nothing here was generated by an LLM.
      </p>

      <div className="mt-8 grid gap-3 md:grid-cols-2">
        {papers.map((p) => (
          <Link key={p.id} href={`/workpapers/${encodeURIComponent(p.workpaperId)}`} className="noise-panel rounded-2xl p-5">
            <p className="font-mono text-[10px] tracking-widest text-[#e8c36a] uppercase">{p.auditSeal}</p>
            <h2 className="font-display mt-1 text-lg font-semibold">{p.workpaperId}</h2>
            <p className="mt-1 text-sm text-[#9aa3b2]">{p.entity} · {p.systemName}</p>
            <p className="font-mono mt-3 truncate text-[11px] text-[#3ee0c5]">{p.merkleRoot}</p>
            <p className="mt-2 text-xs">{p.verified ? "Verified" : "Unverified"}</p>
          </Link>
        ))}
      </div>

      <div className="noise-panel mt-8 overflow-hidden rounded-3xl">
        <div className="border-b border-white/5 px-5 py-3">
          <p className="kicker">Latest events</p>
        </div>
        <div className="overflow-auto">
          <table className="w-full text-left text-sm">
            <thead className="font-mono text-[10px] tracking-widest text-[#9aa3b2] uppercase">
              <tr>
                <th className="px-4 py-2">Ticket</th>
                <th className="px-4 py-2">Verdict</th>
                <th className="px-4 py-2">Proposed</th>
                <th className="px-4 py-2">Paid</th>
                <th className="px-4 py-2">Drift</th>
                <th className="px-4 py-2">Hash</th>
              </tr>
            </thead>
            <tbody>
              {(events.length ? events : on.plays.map((p) => ({
                id: p.ticket.id,
                ticketNumber: p.ticket.ticketNumber,
                verdict: p.verdict,
                proposedAmount: p.proposedAmount,
                paidAmount: p.paidAmount,
                driftScore: p.driftScore,
                stepHash: p.stepHash,
              }))).map((e) => (
                <tr key={e.id} className="border-t border-white/5">
                  <td className="px-4 py-2">#{e.ticketNumber}</td>
                  <td className="px-4 py-2">{e.verdict}</td>
                  <td className="font-mono px-4 py-2">€{Number(e.proposedAmount).toFixed(2)}</td>
                  <td className="font-mono px-4 py-2">€{Number(e.paidAmount).toFixed(2)}</td>
                  <td className="font-mono px-4 py-2">{Number(e.driftScore).toFixed(2)}</td>
                  <td className="font-mono px-4 py-2 text-[11px] text-[#9aa3b2]">{e.stepHash.slice(0, 12)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </main>
  );
}
